# Generated by Django 4.2 on 2023-04-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpoll',
            name='description',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='qpoll',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
