# Generated by Django 4.2 on 2023-04-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0002_alter_qpoll_description_alter_qpoll_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpoll',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='qpoll',
            name='type',
            field=models.CharField(default='active', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('publication_date', models.DateField()),
                ('qpoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpoll.qpoll')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpoll.question')),
            ],
        ),
    ]
