# Generated by Django 4.2 on 2023-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0003_rename_title_qpoll_name_qpoll_type_question_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpoll',
            name='description',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='qpoll',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qpoll',
            name='type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
