# Generated by Django 4.2 on 2023-04-08 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0004_alter_qpoll_description_alter_qpoll_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpoll',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qpoll',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
