# Generated by Django 4.2 on 2023-04-08 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0005_qpoll_created_qpoll_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpoll',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
