# Generated by Django 4.2 on 2023-04-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0008_alter_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qpoll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpoll.qpoll'),
        ),
    ]
